<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="QuanLyBaiViet.aspx.cs" Inherits="TrangTinTucDonGian.Admin.QuanLyBaiViet" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style7 {
            margin-right: 0px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Quản Lý Bài Viết</h1>
     <div id="qlNews">
         <asp:HyperLink ID="HyperLink6" runat="server" NavigateUrl="~/Admin/QuanLyBaiViet.aspx">Quản lí bài viết</asp:HyperLink>
         <asp:HyperLink ID="HyperLink5" runat="server" NavigateUrl="~/Admin/QuanLyUser.aspx">Quản lí User</asp:HyperLink>
         <br />
         <asp:Label ID="Label1" runat="server" Text="News ID :"></asp:Label>
         <asp:DropDownList ID="ddlNewsID" runat="server" DataSourceID="SqlDataSource1" DataTextField="news_ID" DataValueField="news_ID" OnSelectedIndexChanged="ddlNewsID_SelectedIndexChanged">
         </asp:DropDownList>
         <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TrangTinTucConnectionString2 %>" SelectCommand="SELECT [news_ID] FROM [tblNews]"></asp:SqlDataSource>
         <br />
         <asp:Label ID="Label2" runat="server" Text="Category"></asp:Label>
         &nbsp;ID:
         <asp:DropDownList ID="ddlCategory" runat="server" DataSourceID="SqlDataSource2" DataTextField="category_ID" DataValueField="category_ID" OnSelectedIndexChanged="ddlCategory_SelectedIndexChanged">
         </asp:DropDownList>
         <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:TrangTinTucConnectionString %>" SelectCommand="SELECT [category_ID] FROM [tblNews]"></asp:SqlDataSource>
         <br />
         <asp:Label ID="Label3" runat="server" Text="Author ID :"></asp:Label>
         <asp:DropDownList ID="ddlAuthor" runat="server" DataSourceID="SqlDataSource3" DataTextField="author_ID" DataValueField="author_ID" OnSelectedIndexChanged="ddlAuthor_SelectedIndexChanged">
         </asp:DropDownList>
         <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:TrangTinTucConnectionString2 %>" SelectCommand="SELECT [author_ID] FROM [tblNews]"></asp:SqlDataSource>
         <br />
         <asp:Label ID="Label4" runat="server" Text="Title: "></asp:Label>
         <asp:TextBox ID="txtTitle" runat="server" Height="20px"></asp:TextBox>
         <br />
         <asp:Label ID="Label6" runat="server" Text="Image:"></asp:Label>
         <asp:TextBox ID="txtImage" runat="server" Height="20px"></asp:TextBox>
         <br />
         <asp:Label ID="Label5" runat="server" Text="Date: "></asp:Label>
         <asp:TextBox ID="txtDate" runat="server" Height="20px"></asp:TextBox>
         <br />
         <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" />
         &nbsp;&nbsp;&nbsp;
         &nbsp;&nbsp;&nbsp;
         <br />
          &nbsp;&nbsp;&nbsp;
          &nbsp;&nbsp;&nbsp;
         <br />
         <asp:GridView ID="gvNews" runat="server" AutoGenerateColumns="False" CellPadding="4" EnableModelValidation="True" ForeColor="#333333" GridLines="None" OnSelectedIndexChanged="gvNews_SelectedIndexChanged" Width="565px" CssClass="auto-style7" Height="231px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="news_ID" DataSourceID="SqlDataSource4">
             <AlternatingRowStyle BackColor="White" />
             <Columns>
                 <asp:BoundField DataField="news_ID" HeaderText="news_ID" InsertVisible="False" ReadOnly="True" SortExpression="news_ID">
                 </asp:BoundField>
                 <asp:BoundField DataField="category_ID" HeaderText="category_ID" SortExpression="category_ID" />
                 <asp:BoundField DataField="author_ID" HeaderText="author_ID" SortExpression="author_ID" />
                 <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
                 <asp:BoundField DataField="picture" HeaderText="picture" SortExpression="picture" />
                 <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
             </Columns>
             <EditRowStyle BackColor="#7C6F57" />
             <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
             <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
             <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
             <RowStyle BackColor="#E3EAEB" />
             <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
         </asp:GridView>
         <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:TrangTinTucConnectionString2 %>" SelectCommand="SELECT [news_ID], [category_ID], [author_ID], [title], [picture], [date] FROM [tblNews]" UpdateCommand="UPDATE [tblnews] Set [category_ID]=@category_ID, [author_ID]=@author_ID, [title]=@title, [picture]=@picture, [date]=@date Where [news_ID]=@news_ID" DeleteCommand="DELETE FROM [tblnews] where[news_ID]=@news_ID"></asp:SqlDataSource>
         <br />
    </div>
</asp:Content>
