<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="QuanlyUser.aspx.cs" Inherits="TrangTinTucDonGian.Admin.QuanlyUser" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Quản Lý User</h1>
     <div id="qlUser">
        <asp:HyperLink ID="HyperLink6" runat="server" NavigateUrl="~/Admin/QuanLyBaiViet.aspx">Quản lí bài viết</asp:HyperLink>
        <asp:HyperLink ID="HyperLink5" runat="server" NavigateUrl="~/Admin/QuanLyUser.aspx">Quản lí User</asp:HyperLink>
        <br />
        <br />
         <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="user_ID" DataSourceID="SqlDataSource1" EnableModelValidation="True" ForeColor="#333333" GridLines="None" Width="646px" AutoGenerateDeleteButton="True">
             <AlternatingRowStyle BackColor="White" />
             <Columns>
                 <asp:BoundField DataField="user_ID" HeaderText="user_ID" ReadOnly="True" SortExpression="user_ID" />
                 <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                 <asp:BoundField DataField="power" HeaderText="power" SortExpression="power" />
                 <asp:BoundField DataField="fullname" HeaderText="fullname" SortExpression="fullname" />
                 <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                 <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                 <asp:BoundField DataField="phone" HeaderText="phone" SortExpression="phone" />
             </Columns>
             <EditRowStyle BackColor="#7C6F57" />
             <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
             <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
             <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
             <RowStyle BackColor="#E3EAEB" />
             <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
         </asp:GridView>
         <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TrangTinTucConnectionString %>" SelectCommand="SELECT [user_ID], [username], [power], [fullname], [address], [email], [phone] FROM [tblUser]" UpdateCommand="UPDATE [tblUser] Set [username]=@username, [power]=@power, [fullname]=@fullname, [address]=@address, [email]=@email,[phone]=@phone Where [user_ID]=@user_ID" DeleteCommand="DELETE FROM [tblUser] where[user_ID]=@user_ID"></asp:SqlDataSource>
    </div>
</asp:Content>
